# https://docs.github.com/en/actions/guides/publishing-docker-images
name: Publish Docker image
on:
  release:
    types: [published]
    
jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log into Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thearistotle/ban-ad:${{ steps.vars.outputs.tag }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
